#!/bin/sh
device=
. /lib/functions/network.sh
network_flush_cache
network_find_wan6 NET_IF6
network_get_prefix6 NET_ADDR6 "${NET_IF6}"

# Add suffix to IPv6 prefix
device_ipv6=$(echo ${NET_ADDR6} | grep -oE '([0-9a-fA-F]+\:)+')
device_ipv6="${device_ipv6}:$device"

echo "${device_ipv6}"
